version: "3.8"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: msql_admin
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    