version: "3.8"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: msql_admin
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    build: api/.
    restart: always
    ports:
      - 5000:5000
  web:
    build: web/.
    restart: always
    ports:
      - 80:80
